### ISSUE TITLE
Problems with weechat OTR plugin

### ISSUE THREAD

**Issue by irregulator** [TingPing/hexchat-otr#1]
Hi, 
thanks for implementing this plugin. 

I've recently tried it and discovered that there are some issues when my contact uses weechat with https://github.com/mmb/weechat-otr plugin. OTR session seems to be establishing successfully. Then we mutually transmit some OTR messages that are readable in both ends. At random points of time I receive raw OTR messages from my contact, i.e messages starting with "?OTR:". 

I compiled this plugin in Debian jessie, hexchat 2.10.1-1, libotr5 4.1.0-2, if that helps.

Greetings.

**Comment by TingPing** [comment]
Yea the plugin is still in a pretty broken state.
