### ISSUE TITLE
New release planned?

### ISSUE THREAD

**Issue by petterreinholdtsen** [TingPing/hexchat-otr#21]
Hi.  Do you plan to make a new release any time soon?  I wonder if I should wait for a new release before updating the package in Debian, or just pull individual patches on top of 0.2.0.

**Comment by TingPing** [comment]
Done: https://github.com/TingPing/hexchat-otr/releases/tag/0.2.1

**Comment by petterreinholdtsen** [comment]
Thank you very much.  The new version was uploaded to Debian a few minutes ago.  https://packages.qa.debian.org/h/hexchat-otr.html
