### ISSUE TITLE
Seeing mostly "OTR: internal error parsing error string (BUG)"

### ISSUE THREAD

**Issue by dsommers** [TingPing/hexchat-otr#24]
I've tried to build this project on Scientific Linux 7.3 (RHEL 7.3 clone).  I had to reduce the pkg-config version from 0.28 to 0.27, that worked without any visible issues.  But when loading the plug-in and trying to use it, most of the time I only get this response:

```
OTR: internal error parsing error string (BUG)
```

Building against:
```
$ rpm -q glib glib-devel libgcrypt libgcrypt-devel libotr libotr-devel hexchat hexchat-devel
glib-1.2.10-41.el7.x86_64
glib-devel-1.2.10-41.el7.x86_64
libgcrypt-1.5.3-13.el7_3.1.x86_64
libgcrypt-devel-1.5.3-13.el7_3.1.x86_64
libotr-4.1.1-1.el7.x86_64
libotr-devel-4.1.1-1.el7.x86_64
hexchat-2.10.2-1.el7.x86_64
hexchat-devel-2.10.2-1.el7.x86_64
```

Otherwise the build environment is:
```
$ rpm -q gcc glibc pkgconfig
gcc-4.8.5-11.el7.x86_64
glibc-2.17-157.el7_3.1.x86_64
pkgconfig-0.27.1-4.el7.x86_64
```

The build completes, but there are a few warnings here:
```
src/hexchat_otr.c:290:6: warning: no previous prototype for 'hexchat_plugin_get_info' [-Wmissing-prototypes]
 void hexchat_plugin_get_info (char **name, char **desc, char **version, void **reserved)
      ^
src/hexchat_otr.c:297:5: warning: no previous prototype for 'hexchat_plugin_init' [-Wmissing-prototypes]
 int hexchat_plugin_init (hexchat_plugin *plugin_handle,
     ^
src/hexchat_otr.c:328:5: warning: no previous prototype for 'hexchat_plugin_deinit' [-Wmissing-prototypes]
 int hexchat_plugin_deinit (void)
     ^
```

Only giving this a quick look, I have not been able to locate replacement functions for these calls.  Which version of hexchat is this plug-in expected to be built against?

**Comment by TingPing** [comment]
Mind pastebinning `src/otr-formats.h` and `src/hexchat-formats.c` somewhere.

**Comment by dsommers** [comment]
Here you go: https://gist.github.com/dsommers/b24458250731220de79b3cf33630586b

Btw, I'm doing the build from git master (currently based on commit 41fb5767456ccf9121)

**Comment by rpannek** [comment]
I have the exactly same behaviour on Arch Linux.

**Comment by jeena** [comment]
I have exactly the same behaviour on Arch Linux.

**Comment by slashrsm** [comment]
Same here (on Arch)
