### ISSUE TITLE
Format of otr.key: account name

### ISSUE THREAD

**Issue by fred0r** [TingPing/hexchat-otr#7]
Is it really necessary that the name of the current irc-server is used in the account name ?
it would be much nicer that the network-name from hexchat would be used.

i do connect to a znc were every user is configured with multiple irc-servers.
in case the bouncer reconnects to another server i need to create a new key pair.

**Comment by petterreinholdtsen** [comment]
I ran into this problem today, and I agree.  I connect to irc.freenode.net, which maps to chat.freenode.net, which is mapped to several servers using round robin DNS.  and every time I reconnect, I get a new server and need a new otr key. :(

**Comment by dramb-lys** [comment]
This issue currently makes hexchat-otr unusable for me. I currently have multiple keys for the same identity (same nick on the same network). This leads to excessive key regeneration and, more importantly, loss of trusted connections.

Key contexts should arguably be tied to nick@network rather than nick@server-host.

**Comment by TingPing** [comment]
I agree that the network name is the logical choice.

**Comment by dramb-lys** [comment]
I think this is currently the most pressing issue.

**Comment by TingPing** [comment]
Patches welcomed.

**Comment by fred0r** [comment]
Come on - this sounds trivial - i am just a user :/

**Comment by fred0r** [comment]
hexchat-otr/src/hexchat_otr.c
const char *server = hexchat_get_info (ph, "server");
to
const char *server = hexchat_get_info (ph, "network");

**Comment by TingPing** [comment]
What about migrating old keys?

**Comment by petterreinholdtsen** [comment]
[TingPing]
> What about migrating old keys?

I've got so many old keys, they keys do not really make sense.  So I
would suggest to just ignore the old keys and create a new one, like the
plugin have done too many times already in the past.

I guess it is just as important to remove the no longer relevant keys
from the file, but it isn't a big deal either.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by fred0r** [comment]
Yes - i do also own sooooo many autocreated keys.
A clean start is the best.

**Comment by petterreinholdtsen** [comment]
[fred]
> hexchat-otr/src/hexchat_otr.c
> const char *server = hexchat_get_info (ph, "server");
> to
> const char *server = hexchat_get_info (ph, "network");

Perhaps you can prepare a tested patch doing this?  Here is an untested
patch.  It compiled, but that all the testing I could give it right now.

I would love to include such patch in Debian if TingPing do not have
time to make a new release.

diff --git a/src/hexchat_otr.c b/src/hexchat_otr.c
index d6c82b7..8c92e75 100644
--- a/src/hexchat_otr.c
+++ b/src/hexchat_otr.c
@@ -49,10 +49,10 @@ static int cmd_otr (char *word[], char *word_eol[], void *userdata)
 {
 	const char *own_nick = hexchat_get_info (ph, "nick");
 	char *target = (char *)hexchat_get_info (ph, "channel");
-	const char *server = hexchat_get_info (ph, "server");
+	const char *network = hexchat_get_info (ph, "network");
 	IRC_CTX ircctxs = {
 				.nick = (char *)own_nick,
-				.address = (char *)server
+				.address = (char *)network
 			},
 			*ircctx = &ircctxs;
 
@@ -174,12 +174,12 @@ static int hook_outgoing (char *word[], char *word_eol[], void *userdata)
 {
 	const char *own_nick = hexchat_get_info (ph, "nick");
 	const char *channel = hexchat_get_info (ph, "channel");
-	const char *server = hexchat_get_info (ph, "server");
+	const char *network = hexchat_get_info (ph, "network");
 	char newmsg[512];
 	char *otrmsg;
 	IRC_CTX ircctx = {
 		.nick = (char *)own_nick,
-		.address = (char *)server
+		.address = (char *)network
 	};
 
 	if (get_current_context_type () != 3) /* Not PM */
@@ -209,12 +209,12 @@ static int hook_privmsg (char *word[], char *word_eol[], void *userdata)
 {
 	char nick[256];
 	char *newmsg;
-	const char *server = hexchat_get_info (ph, "server");
+	const char *network = hexchat_get_info (ph, "network");
 	const char *own_nick = hexchat_get_info (ph, "nick");
 	const char *chantypes = hexchat_list_str (ph, NULL, "chantypes");
 	IRC_CTX ircctx = {
 		.nick = (char *)own_nick,
-		.address = (char *)server
+		.address = (char *)network
 	};
 	hexchat_context *query_ctx;
 
@@ -239,11 +239,11 @@ static int hook_privmsg (char *word[], char *word_eol[], void *userdata)
 		return HEXCHAT_EAT_NONE;
 	}
 
-	query_ctx = hexchat_find_context (ph, server, nick);
+	query_ctx = hexchat_find_context (ph, network, nick);
 	if (query_ctx == NULL)
 	{
 		hexchat_commandf (ph, "query %s", nick);
-		query_ctx = hexchat_find_context (ph, server, nick);
+		query_ctx = hexchat_find_context (ph, network, nick);
 	}
 
 	GRegex *regex_quot = g_regex_new ("&quot;", 0, 0, NULL);
@@ -333,19 +333,19 @@ void printformat (IRC_CTX *ircctx, const char *nick, int lvl, int fnum, ...)
 	va_start (params, fnum);
 	char msg[LOGMAX], *s = msg;
 	hexchat_context *find_query_ctx;
-	char *server = NULL;
+	char *network = NULL;
 
 	if (ircctx)
-		server = ircctx->address;
+		network = ircctx->address;
 
-	if (server && nick)
+	if (network && nick)
 	{
-		find_query_ctx = hexchat_find_context (ph, server, nick);
+		find_query_ctx = hexchat_find_context (ph, network, nick);
 		if (find_query_ctx == NULL)
 		{
 			/* no query window yet, let's open one */
 			hexchat_commandf (ph, "query %s", nick);
-			find_query_ctx = hexchat_find_context (ph, server, nick);
+			find_query_ctx = hexchat_find_context (ph, network, nick);
 		}
 	}
 	else
@@ -354,7 +354,7 @@ void printformat (IRC_CTX *ircctx, const char *nick, int lvl, int fnum, ...)
 											   NULL,
 											   hexchat_get_info (ph,
 																 "network")
-												   ?: hexchat_get_info (ph, "server"));
+												   ?: hexchat_get_info (ph, "network"));
 	}
 
 	hexchat_set_context (ph, find_query_ctx);

-- 
Happy hacking
Petter Reinholdtsen

**Comment by TingPing** [comment]
@petterreinholdtsen I will accept it if somebody tests it, I don't even use this plugin that is why I have not done this myself.

**Comment by fred0r** [comment]
I'm using that fix for some days now - no problems so far.

**Comment by fred0r** [comment]
Thank you !

**Comment by petterreinholdtsen** [comment]
Very good to see this issue fixed.  Do you plan a new release soon with
this change included?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by TingPing** [comment]
I'll make a release soon if I don't get any new complaints.
