### ISSUE TITLE
Plugin files install to wrong directory on x86_64 system

### ISSUE THREAD

**Issue by zeriam** [TingPing/hexchat-otr#8]
The `make install` command installs the plugin files to `/usr/local/lib/hexchat/plugins` on my x86_64 system, but the correct plugin directory is `/usr/lib/x86_64-linux-gnu/hexchat/plugins`.  This may be resolved by installing the plugin files to `~/.config/hexchat/addons`, but consideration of custom config directories may need to be considered.

This message prints when `autogen.sh` runs:
`checking for hexchat's plugin path... not found, assuming ${exec_prefix}/lib/hexchat/plugins`.

**Comment by TingPing** [comment]
Not much can be done about that, if hexchat is installed the plugin grabs the real install dir via `pkg-config --variable=hexchatlibdir hexchat-plugin`. If that is not installed it is just a guessing game and `$libdir` is the default for all of this, distros that do this custom libdir probably usually call `./configure --libdir=.../x86_64-linux-gnu/...` which will continue to work fine.

**Comment by zeriam** [comment]
Why can't you use `~/.config/hexchat/addons`?

**Comment by TingPing** [comment]
Well I always want the ability to install system wide for the various packages in distros, a separate command for local installs would be reasonable though.
