### ISSUE TITLE
hexchat-otr ready for Debian?

### ISSUE THREAD

**Issue by petterreinholdtsen** [TingPing/hexchat-otr#9]
Hi.  I just discovered this plugin, and tested it in Debian.  It seem to be working, but the open issue (IRC server name used when creating key) make me unsure if it is ready for a wider audience.  Do you believe it is ready to become part of Debian?

Are there other hexchat plugins for OTR available?  I found some github repos, but they all have different maturity levels.

**Comment by TingPing** [comment]
> Are there other hexchat plugins for OTR available? I found some github repos, but they all have different maturity levels.

They are all likely forks of `xchat-otr`, my fork is surely had the most progress by now. Is it ready for general use.. I honestly don't know, I barely use it so I would say probably not.

**Comment by petterreinholdtsen** [comment]
OK.

I asked if hexchat would add OTR support in https://github.com/hexchat/hexchat/issues/1610 , and discovered a python plugin available from https://github.com/SpiralP/HexChat-otr/ .  Perhaps that one is more mature.  I have not tested it yet.

**Comment by TingPing** [comment]
Mature certainly isn't the right word. xchat-otr is like a decade old and libotr is rather old (which has been security audited before).

**Comment by TingPing** [comment]
@petterreinholdtsen I made a versioned release so you can at least make an unofficial package:  https://github.com/TingPing/hexchat-otr/releases/tag/0.2.0

**Comment by petterreinholdtsen** [comment]
[TingPing]
> @petterreinholdtsen I made a versioned release so you can at least
> make an unofficial package:
> https://github.com/TingPing/hexchat-otr/releases/tag/0.2.0

Thank you very much.  I'll wrap up my Debian build rules and publish
them.  Btw, what about making the hexchat-otr repo visible under the
hexchat github project?  It would probably increase the visibility and
get more eyeballs to look at the code.

--
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
[Petter Reinholdtsen]
> Thank you very much.  I'll wrap up my Debian build rules and publish
> them.  Btw, what about making the hexchat-otr repo visible under the
> hexchat github project?  It would probably increase the visibility and
> get more eyeballs to look at the code.

Hm, the AX_APPEND_COMPILE_FLAGS autoconf macro seem to be missing.  Any
idea where it should come from?  Without it, I get this failure:

checking for hexchat's plugin path... /usr/lib/x86_64-linux-gnu/hexchat/plugins
./configure: line 12232: syntax error near unexpected token `-std=gnu99'
./configure: line 12232: `      -std=gnu99 \'
%

-- 
Happy hacking
Petter Reinholdtsen

**Comment by TingPing** [comment]
Sounds like you used the wrong tarball, releases have all macros bundled.

**Comment by petterreinholdtsen** [comment]
[TingPing]
> Sounds like you used the wrong tarball, releases have all macros
> bundled.

I'm using the git repo.  What is the source for that macro.  I'm
probably missing some dependency.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by TingPing** [comment]
It is a part of `autoconf-archive`.

(also please stop replying to github via email, it just comes out with crap formatting I have to fix)

**Comment by petterreinholdtsen** [comment]
Thank you for the tip about autoconf-archive.  Now the Debian package
build. :)

The Debian build rules are now available from
<URL: https://github.com/petterreinholdtsen/hexchat-otr-c/tree/debian >.
A proper build setup would probably use git-buildpackage instead of a
branch based on the upstream git repo.

Sorry for the extra work a text/plain email causes, but using the web
interface is often not practical for me, so dropping email replies is
not going to work.

--
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
Despites my doubts, I have decided to package this for Debian, to make
the package I use available for everyone.  See the Debian request at
<URL: http://bugs.debian.org/815059 >.

JFYI.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
[Petter Reinholdtsen]
> Despites my doubts, I have decided to package this for Debian, to make
> the package I use available for everyone.  See the Debian request at
> <URL: http://bugs.debian.org/815059 >.

And since earlier today, hechat-otr is available in Debian unstable,
<URL: https://tracker.debian.org/pkg/hexchat-otr >.
-- 
Happy hacking
Petter Reinholdtsen
